-- Scheduled digests (agentboom package: digests) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS digests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    prompt TEXT NOT NULL,
    interval_min INTEGER,               -- simple schedule
    cron_expr TEXT,                     -- takes precedence when set
    enabled INTEGER NOT NULL DEFAULT 1,
    last_run_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS digest_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_id BIGINT NOT NULL REFERENCES digests(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK(kind IN ('feed', 'emails', 'endpoint')),
    ref TEXT NOT NULL,                  -- feed URL / 'limit:20' / endpoint URL
    note TEXT,
    UNIQUE(digest_id, kind, ref)
);

CREATE TABLE IF NOT EXISTS digest_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_id BIGINT NOT NULL REFERENCES digests(id) ON DELETE CASCADE,
    ran_at TIMESTAMPTZ DEFAULT NOW(),
    content TEXT NOT NULL,
    delivered INTEGER NOT NULL DEFAULT 0,
    error TEXT
);
CREATE INDEX IF NOT EXISTS idx_digest_runs ON digest_runs(digest_id, ran_at DESC);
