-- Email foundation (agentboom package: email) — PostgreSQL variant.
-- Mailbox passwords are NOT stored here — they live in the vault under
-- the service name 'email:<address>'.

CREATE TABLE IF NOT EXISTS email_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    provider TEXT NOT NULL DEFAULT 'imap',
    imap_host TEXT NOT NULL,
    imap_port INTEGER NOT NULL DEFAULT 993,
    smtp_host TEXT,
    smtp_port INTEGER,
    enabled INTEGER NOT NULL DEFAULT 1,
    last_sync_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES email_accounts(id) ON DELETE CASCADE,
    folder TEXT NOT NULL DEFAULT 'INBOX',
    uid TEXT NOT NULL,
    message_id TEXT,
    from_email TEXT,
    from_name TEXT,
    subject TEXT,
    received_at TIMESTAMPTZ,
    has_attachment INTEGER NOT NULL DEFAULT 0,
    body_text TEXT,
    UNIQUE(account_id, folder, uid)
);
CREATE INDEX IF NOT EXISTS idx_emails_received ON emails(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_emails_from ON emails(from_email);

CREATE TABLE IF NOT EXISTS email_filters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    match_from TEXT,          -- case-insensitive substring on sender
    match_subject TEXT,       -- case-insensitive substring on subject
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- The receipts: a filter with no record of what it dropped is
-- indistinguishable from a bug. Subject + sender only — the message
-- itself was the thing not kept.
CREATE TABLE IF NOT EXISTS email_filter_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filter_name TEXT NOT NULL,
    account_email TEXT NOT NULL,
    from_email TEXT,
    subject TEXT,
    skipped_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_filter_log_at ON email_filter_log(skipped_at DESC);
