-- Reminders (agentboom package: reminders) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    due_at TIMESTAMPTZ NOT NULL,
    recurrence TEXT,
    delivered INTEGER NOT NULL DEFAULT 0,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reminders_due ON reminders(due_at);
