"""How the assistant identifies itself in anything it writes to a human.

One rule, and it is not stylistic:

    **The assistant never signs as the principal.**

Everything the platform sends — a report, a reply the queue sent from the
principal's mailbox, whatever the next mini-app sends — goes out identified
as *the assistant of* the principal. A message a person did not write must
not carry that person's name at the bottom, because the recipient uses the
signature to decide who they are talking to.

It lives in the SDK rather than in the mini-app that needed it first,
because a convention that exists in one file is a convention the next
mini-app will not know about. The send path enforces it at the point of no
return (see `signs_as_principal`).

    from agentboom_sdk import voice

    body = voice.sign(draft, language="pt")     # deterministic sign-off
    hello = voice.greeting("pt")                # "Bom dia" / "Boa tarde" / …

The sign-off is never generated by a model — it is the one part of a message
whose wording must never drift. The principal's name is not hard-coded: it
comes from the profile (`profile.json` user.name) or the
ASSISTANT_PRINCIPAL env override, so the SDK is not personally about anyone.
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from zoneinfo import ZoneInfo

from agentboom_sdk import profile as _profile

DEFAULT_LANGUAGE = "en"

#: (last hour of the morning, last hour of the afternoon, the three greetings).
#: The boundaries genuinely differ per language; a single shared cutoff would
#: be wrong in all of them.
_GREETINGS = {
    "pt": (13, 20, ("Bom dia", "Boa tarde", "Boa noite")),
    "en": (12, 18, ("Good morning", "Good afternoon", "Good evening")),
    "es": (13, 20, ("Buenos días", "Buenas tardes", "Buenas noches")),
    "fr": (18, 18, ("Bonjour", "Bonjour", "Bonsoir")),
}

#: valediction, who is signing, and the small print. `{principal}` is filled
#: in. Three small-print variants per language: written by the assistant,
#: sent automatically, and reviewed by the principal.
_SIGN_OFF = {
    "pt": ("Com os melhores cumprimentos,", "Assistente de {principal}",
           "Para falar diretamente com {principal}, basta responder a este email.",
           "Mensagem enviada automaticamente em nome de {principal}. "
           "Para falar diretamente com {principal}, basta responder a este email.",
           "Mensagem revista por {principal}. "
           "Para falar diretamente com {principal}, basta responder a este email."),
    "en": ("Kind regards,", "Assistant to {principal}",
           "To speak directly with {principal}, just reply to this email.",
           "Sent automatically on behalf of {principal}. "
           "To speak directly with {principal}, just reply to this email.",
           "Reviewed by {principal}. "
           "To speak directly with {principal}, just reply to this email."),
    "es": ("Saludos cordiales,", "Asistente de {principal}",
           "Para hablar directamente con {principal}, basta responder a este correo.",
           "Mensaje enviado automáticamente en nombre de {principal}. "
           "Para hablar directamente con {principal}, basta responder a este correo.",
           "Mensaje revisado por {principal}. "
           "Para hablar directamente con {principal}, basta responder a este correo."),
    "fr": ("Cordialement,", "Assistant de {principal}",
           "Pour échanger directement avec {principal}, il suffit de répondre à cet email.",
           "Message envoyé automatiquement au nom de {principal}. "
           "Pour échanger directement avec {principal}, il suffit de répondre à cet email.",
           "Message relu par {principal}. "
           "Pour échanger directement avec {principal}, il suffit de répondre à cet email."),
}

_SIGN_OFF_KEYS = ("valediction", "who", "written", "automated", "reviewed")

#: Per-language wording overrides. Absent file = the built-in wording above.
SIGNOFF_FILE = Path(os.environ.get(
    "ASSISTANT_SIGNOFF_FILE",
    str(Path(os.environ.get("DATA_DIR", "data")) / "email-signoff.json")))

_override_words: Optional[Dict[str, Dict[str, str]]] = None
_override_mtime: Optional[float] = None


# ── identity (from profile / env, never hard-coded) ────────────────

def get_principal() -> str:
    """Who the assistant acts for. Env override, else the profile name."""
    return (os.environ.get("ASSISTANT_PRINCIPAL")
            or _profile.user_name()
            or "the principal")


def _tz():
    """The principal's clock, for time-of-day greetings."""
    try:
        return ZoneInfo(_profile.effective_timezone())
    except Exception:  # noqa: BLE001 — bad/unknown zone
        return timezone.utc


def _default_language() -> str:
    env_lang = os.environ.get("ASSISTANT_LANGUAGE", "").strip().lower()
    if env_lang and env_lang != "auto":
        return env_lang[:2]
    prof_lang = (_profile.language() or "").strip().lower()
    if prof_lang and prof_lang != "auto":
        return prof_lang[:2]
    return DEFAULT_LANGUAGE


def _language(language: Optional[str]) -> str:
    code = (language or _default_language()).strip().lower()[:2]
    return code if code in _SIGN_OFF else DEFAULT_LANGUAGE


# ── wording (built-ins + editable overrides) ───────────────────────

def _load_overrides() -> Dict[str, Dict[str, str]]:
    global _override_words, _override_mtime
    try:
        mtime = SIGNOFF_FILE.stat().st_mtime
    except OSError:
        _override_words, _override_mtime = {}, None
        return _override_words
    if _override_words is None or mtime != _override_mtime:
        try:
            data = json.loads(SIGNOFF_FILE.read_text())
            _override_words = data if isinstance(data, dict) else {}
        except (OSError, json.JSONDecodeError):
            _override_words = {}
        _override_mtime = mtime
    return _override_words


def builtin_words(language: Optional[str] = None) -> Dict[str, str]:
    code = _language(language)
    return dict(zip(_SIGN_OFF_KEYS, _SIGN_OFF[code]))


def sign_off_words(language: Optional[str] = None) -> Dict[str, str]:
    code = _language(language)
    words = builtin_words(code)
    override = _load_overrides().get(code) or {}
    for key in _SIGN_OFF_KEYS:
        value = override.get(key)
        if isinstance(value, str) and value.strip():
            words[key] = value
    return words


_VALEDICTIONS = (
    "com os melhores cumprimentos", "os melhores cumprimentos", "melhores cumprimentos",
    "cumprimentos", "atenciosamente", "obrigado", "obrigada", "abraço", "abraços",
    "kind regards", "best regards", "warm regards", "regards", "best wishes",
    "sincerely", "yours sincerely", "yours faithfully", "thanks", "thank you",
    "saludos cordiales", "saludos", "atentamente", "gracias",
    "cordialement", "bien cordialement", "sincèrement", "merci",
)


def greeting(language: Optional[str] = None, when: Optional[datetime] = None) -> str:
    """A time-of-day greeting by the principal's clock (scheduled mail goes
    out at a fixed hour, so a hard-coded greeting is wrong most of the day)."""
    morning, afternoon, words = _GREETINGS[_language(language)]
    hour = (when or datetime.now(_tz())).astimezone(_tz()).hour
    return words[0] if hour < morning else words[1] if hour < afternoon else words[2]


def sign_off(
    language: Optional[str] = None, *,
    principal: Optional[str] = None,
    automated: bool = False,
    reviewed: bool = False,
) -> List[str]:
    """The closing lines, as text. The assistant, never the person."""
    words = sign_off_words(language)
    name = principal or get_principal()
    small = (words["reviewed"] if reviewed
             else words["automated"] if automated
             else words["written"])
    return [words["valediction"], _fmt(words["who"], name), "",
            _fmt(small, name)]


def _fmt(template: str, name: str) -> str:
    try:
        return template.format(principal=name)
    except (KeyError, IndexError, ValueError):
        return template.replace("{principal}", name)


def _valediction_set() -> Tuple[str, ...]:
    extras = []
    for override in _load_overrides().values():
        valediction = (override or {}).get("valediction")
        if isinstance(valediction, str) and valediction.strip():
            extras.append(valediction.strip().rstrip(",.!").lower())
    return _VALEDICTIONS + tuple(sorted(set(extras)))


def signs_as_principal(text: str, principal: Optional[str] = None) -> bool:
    """Does this text end by signing as the person, rather than the assistant?
    Only the tail is examined, and only whole lines."""
    name = (principal or get_principal()).strip()
    first = name.split()[0].lower() if name.split() else ""
    wanted = {name.lower(), first} - {""}
    lines = [line for line in (text or "").splitlines() if line.strip()]
    for line in lines[-4:]:
        if _bare_name(line) in wanted:
            return True
    return False


def _bare_name(line: str) -> str:
    stripped = line.strip().strip("*_")
    stripped = re.sub(r"^[\-–—~>\s]+", "", stripped)
    stripped = re.sub(r"[.,;:!\s]+$", "", stripped)
    return stripped.lower() if len(stripped) <= 40 else ""


#: Second-person-singular informal forms (Portuguese "tu"). Deliberately
#: narrow — precision matters more than recall at a send gate.
_INFORMAL_PT = re.compile(
    r"\b(?:teu|tua|teus|tuas|podes|podias|contigo"
    r"|fizeste|disseste|enviaste|mandaste|escreveste|recebeste|pediste"
    r"|quiseste|soubeste|tiveste|viste|foste|estavas|sabias|querias)\b",
    re.IGNORECASE,
)


def informal_markers(text: str, language: Optional[str] = None) -> List[str]:
    """Informal forms found in a draft, lowercased and deduped (pt only)."""
    if _language(language) != "pt":
        return []
    return sorted({m.group(0).lower() for m in _INFORMAL_PT.finditer(text or "")})


def sign(
    text: str, language: Optional[str] = None, *,
    principal: Optional[str] = None,
    automated: bool = False,
    reviewed: bool = False,
) -> str:
    """Return `text` closed with the assistant's sign-off.

    Idempotent and re-signable: an existing valediction and any line that is
    just the principal's name are removed first, so re-signing replaces the
    closing block rather than stacking a second one.
    """
    lines = (text or "").rstrip().splitlines()
    closing = sign_off(language, principal=principal,
                       automated=automated, reviewed=reviewed)
    who = closing[1]
    valedictions = _valediction_set()
    name = (principal or get_principal()).strip()

    for i in range(len(lines) - 1, max(len(lines) - 8, -1), -1):
        if lines[i].strip() == who:
            start = i - 1 if i > 0 and \
                _bare_name(lines[i - 1]).rstrip(",") in valedictions else i
            lines = lines[:start]
            break

    wanted = {name.lower(), name.split()[0].lower() if name.split() else ""} - {""}
    known_whos = set()
    for code in _SIGN_OFF:
        known_whos.add(_fmt(builtin_words(code)["who"], name).strip().lower())
    for override in _load_overrides().values():
        who_template = (override or {}).get("who")
        if isinstance(who_template, str) and who_template.strip():
            known_whos.add(_fmt(who_template, name).strip().lower())

    while lines:
        tail = _bare_name(lines[-1])
        if not tail:
            if lines[-1].strip():
                break
            lines.pop()
            continue
        if tail in wanted or tail in known_whos or \
                tail.rstrip(",") in valedictions:
            lines.pop()
            continue
        break

    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines + [""] + closing).rstrip() + "\n"
