-- Email templates (agentboom package: email-templates) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_email TEXT,
    name TEXT NOT NULL,
    html TEXT NOT NULL,
    description TEXT,
    season TEXT,
    is_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_email_tpl_scope_name
    ON email_templates(COALESCE(scope_email, '*'), name);

CREATE TABLE IF NOT EXISTS email_template_active (
    account_email TEXT PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES email_templates(id) ON DELETE CASCADE,
    activated_at TIMESTAMPTZ DEFAULT NOW()
);
