-- Email templates (agentboom package: email-templates) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    scope_email TEXT,                 -- NULL = shared across all mailboxes
    html TEXT NOT NULL,
    description TEXT,
    season TEXT,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_template_active (
    account_email TEXT PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES email_templates(id) ON DELETE CASCADE,
    activated_at TIMESTAMPTZ DEFAULT NOW()
);
