-- Credential vault (agentboom package: vault) — PostgreSQL variant.
-- Used instead of 002_vault.sql when DATABASE_URI points at PostgreSQL.

CREATE TABLE IF NOT EXISTS vault_credentials (
    service TEXT PRIMARY KEY,
    encrypted BYTEA NOT NULL,
    nonce BYTEA NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_decrypted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS vault_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service TEXT NOT NULL,
    action TEXT NOT NULL,
    detail TEXT,
    at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_vault_audit_service ON vault_audit(service, id DESC);
