-- RSS/Atom feed watching (agentboom package: rss-feeds) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    title TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    last_fetched_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feed_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
    guid TEXT NOT NULL,
    title TEXT,
    link TEXT,
    summary TEXT,
    published TEXT,
    seen_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(feed_id, guid)
);
CREATE INDEX IF NOT EXISTS idx_feed_items_seen ON feed_items(seen_at DESC);
