-- Document collections (agentboom package: documents) — PostgreSQL variant.
-- Collections and their matching rules are API-managed: one engine,
-- any number of use cases (invoices, receipts, warranties, contracts).

CREATE TABLE IF NOT EXISTS document_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    match_from TEXT,          -- case-insensitive substring on sender
    match_subject TEXT,       -- case-insensitive substring on subject
    note TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL
        REFERENCES document_collections(id) ON DELETE CASCADE,
    source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('email', 'manual')),
    email_id BIGINT,                    -- set when source = 'email'
    title TEXT NOT NULL,
    notes TEXT,
    file_name TEXT,                     -- optional: a storage package file
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(collection_id, email_id)
);
CREATE INDEX IF NOT EXISTS idx_documents_collection ON documents(collection_id);
