#!/usr/bin/env python3
"""Sync generated content into the agentboom-website repo.

Usage:
    python3 scripts/sync_website.py /path/to/agentboom-website

Does two things, both idempotent:
1. Copies docs/*.md into <website>/content/ (commands, anatomy, roadmap)
   so the site never drifts from the docs in this repo.
2. Renders <website>/content/packages.md from every package's
   .agentboom-package.json — the listing is generated, never hand-written.

Stdlib only. Run by the website's deploy pipeline before `docker build`,
so agentboom.dev always shows the current base.
"""
import json
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS_SRC = REPO / "docs"
TEMPLATES = REPO / "src" / "agentboom" / "templates"
PACKAGES_ROOTS = [
    TEMPLATES / "packages",    # addons
    TEMPLATES / "connectors",  # external-service integrations
]
SYNC_DOCS = ("commands.md", "anatomy.md", "framework.md", "frontend.md")

GENERATED_BANNER = (
    "<!-- GENERATED by agentboom scripts/sync_website.py — do not edit. -->\n"
)


def load_packages() -> list:
    out = []
    for root in PACKAGES_ROOTS:
        if not root.is_dir():
            continue
        # depth-1 and depth-2 (category) package dirs
        pkg_dirs = [d for d in root.iterdir() if d.is_dir()]
        for cat in [d for d in pkg_dirs if not (d / ".agentboom-package.json").is_file()]:
            pkg_dirs += [d for d in sorted(cat.iterdir()) if d.is_dir()]
        for pkg_dir in sorted(pkg_dirs):
            meta_path = pkg_dir / ".agentboom-package.json"
            if not meta_path.is_file():
                continue
            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                print(f"warning: bad meta {meta_path}: {exc}", file=sys.stderr)
                continue
            meta.setdefault("name", pkg_dir.name)
            meta["_dir"] = pkg_dir
            out.append(meta)
    return out


def env_vars(meta: dict) -> list:
    names = []
    for line in meta.get("env_example", []):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=", stripped)
        if m:
            names.append(m.group(1))
    return names


def derender(text: str) -> str:
    """Package text is a template; the site shows generic placeholders."""
    return (text.replace("{{PORT_PLATFORM}}", "<platform-port>")
                .replace("{{PORT_AGENT}}", "<agent-port>")
                .replace("{{AGENT_NAME}}", "<agent-name>")
                .replace("{{AGENT_TITLE}}", "<agent-title>"))


def render_packages_md(packages: list) -> str:
    lines = [
        GENERATED_BANNER,
        "# Packages",
        "",
        "Capabilities install into any agent with one command — files are "
        "copied (never overwritten), requirements and env lines are "
        "appended, and post-install steps are printed:",
        "",
        "```bash",
        "agentboom add package <name>",
        "```",
        "",
        "Packages can declare dependencies (`requires`); install refuses "
        "to run when they are missing. Extra package sources — any git "
        "repo or directory — join with `agentboom registries add`.",
        "",
        "The at-a-glance catalog lives on the site's **Packages** page; "
        "this page is the how-to: what each package needs and how to "
        "finish its setup, plus how to write your own.",
        "",
    ]

    groups = [
        ("Connectors", [p for p in packages if p.get("kind") == "connector"]),
        ("Add-ons", [p for p in packages if p.get("kind") != "connector"]),
    ]
    for title, group in groups:
        if not group:
            continue
        lines += [f"## {title}", ""]
        if title == "Connectors":
            lines += [
                "Connectors also install an importable client under "
                "`platform/connectors/<name>/`, so mini-apps can use them:",
                "",
            ]
        for pkg in group:
            icon = f"{pkg['icon']} " if pkg.get("icon") else ""
            lines += [f"### {icon}`{pkg['name']}`", "",
                      derender(pkg.get("description", "")), ""]
            requires = pkg.get("requires") or []
            if requires:
                lines.append(f"**Requires:** {', '.join(f'`{r}`' for r in requires)}  ")
            reqs = pkg.get("requirements") or []
            if reqs:
                lines.append(f"**Adds dependencies:** {', '.join(f'`{r}`' for r in reqs)}  ")
            variables = env_vars(pkg)
            if variables:
                lines.append(f"**Env to fill in `.env`:** {', '.join(f'`{v}`' for v in variables)}  ")
            if requires or reqs or variables:
                lines.append("")
            post = pkg.get("post_install") or []
            if post:
                lines.append("Setup:")
                lines.append("")
                for step in post:
                    lines.append(f"- {derender(step)}")
                lines.append("")
    lines += [
        "## Make your own package",
        "",
        "A package is a folder in `templates/packages/<name>/` with:",
        "",
        "- `.agentboom-package.json` — name, icon, description, `kind` "
        "(`connector` also installs an importable client under "
        "`platform/connectors/<name>/`), `requirements`, `env_example`, "
        "`requires`, `post_install` steps;",
        "- the files it places, mirroring agent paths (`platform/...`, "
        "`.qwen-docker/...`), rendered with the agent's init variables.",
        "",
        "Install semantics: files are copied without overwriting, "
        "requirement and env lines are appended idempotently, and "
        "`post_install` steps are printed for the human/agent to finish.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    website = Path(sys.argv[1]).expanduser().resolve()
    content = website / "content"
    if not content.is_dir():
        print(f"error: {content} not found — is this the agentboom-website repo?",
              file=sys.stderr)
        return 1

    for name in SYNC_DOCS:
        src = DOCS_SRC / name
        if src.is_file():
            shutil.copyfile(src, content / name)
            print(f"synced docs/{name} -> content/{name}")

    packages = load_packages()
    (content / "packages.md").write_text(render_packages_md(packages),
                                         encoding="utf-8")
    print(f"generated content/packages.md ({len(packages)} packages)")

    catalog = [
        {
            "name": pkg["name"],
            "icon": pkg.get("icon", ""),
            "description": derender(pkg.get("description", "")),
            "kind": pkg.get("kind", "add-on"),
            "requires": pkg.get("requires") or [],
            "install": f"agentboom add package {pkg['name']}",
        }
        for pkg in packages
    ]
    (content / "packages-catalog.json").write_text(
        json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    print(f"generated content/packages-catalog.json ({len(catalog)} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
