-- Google OAuth accounts (agentboom package: google) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS google_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    scope TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_refresh_at TIMESTAMPTZ
);
