-- Durable knowledge notes (agentboom package: knowledge) — PostgreSQL variant.

CREATE TABLE IF NOT EXISTS knowledge_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    tags TEXT NOT NULL DEFAULT '',      -- comma-separated, lowercase
    source TEXT,                        -- where the fact came from
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_updated ON knowledge_notes(updated_at DESC);
